name: gobabel_core
description: All core functionalities of the GO-Babel project. This package is used by the CLI and the client.
version: 1.0.0
repository: https://github.com/Go-Babel/gobabel_core
issue_tracker: https://github.com/Go-Babel/gobabel_core/issues

environment:
  sdk: ^3.7.2 

dependencies:
  path: ^1.9.1
  chalkdart: ^3.0.5
  
dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2