name: gobabel_core
description: All core functionalities of the GO-Babel project. This package is used by the CLI and the client.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.7.2 

dependencies:
  path: ^1.9.1
dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0