name: gobabel_core
description: All core functionalities of the GO-Babel project. This package is used by the CLI and the client.
version: 1.0.3
# Ready to publish to pub.dev when needed (dependency of gobabel CLI)
# publish_to: 'https://pub.dev'
repository: https://github.com/Go-Babel/gobabel_core
issue_tracker: https://github.com/Go-Babel/gobabel_core/issues

environment:
  sdk: ^3.8.1

resolution: workspace

dependencies:
  path: ^1.9.1
  recase: ^4.1.0
  result_dart: ^2.1.1
  chalkdart: ^3.0.5
  crypto: ^3.0.6
  gobabel_client: any
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  
dev_dependencies:
  freezed: ^3.2.0
  build_runner: ^2.6.1
  json_serializable: ^6.10.0
  lints: ^5.0.0
  test: ^1.24.0